services:
  app:
    build: ./
    container_name: wallet
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: wallet-psql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=wallet
    ports:
      - "5432:5432"